repos:
  - repo: https://github.com/psf/black
    rev: 23.9.0
    hooks:
      - id: black
        language_version: python3.10
        args: ["--line-length=9999"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--trailing-comma", "--multi-line=3", "--skip=third_party", "--skip-gitignore", "--use-parentheses"]
        exclude: \.py-tpl$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==23.9.0
