agent_name: "BaselinePG"

model:
  actor_net: "fc_2layers_64units"
  actor_init_output_scale: 0.01
  actor_std_type: "FIXED"
  action_std: 0.2
  critic_net: "fc_2layers_64units"

discount: 0.95
steps_per_iter: 5000 # number of steps of interaction per iteration, also buffer size
iters_per_output: 1
test_episodes: 32
critic_update_epoch: 5

# optimizer parameters
actor_learning_rate: 0.01
critic_learning_rate: 0.01

batch_size: 400
norm: False
norm_adv_clip: 1.0
action_bound_weight: 0