agent_name: "VanillaPG"

model:
  actor_net: "fc_1layers_32units"
  actor_init_output_scale: 0.01
  actor_std_type: "FIXED"
  action_std: 0.2

discount: 0.95
steps_per_iter: 4000 # number of steps of interaction per iteration, also buffer size
iters_per_output: 1
test_episodes: 32

# optimizer parameters
actor_learning_rate: 5e-3

batch_size: 400
norm: False
norm_Q_clip: 1.0
action_bound_weight: 0